profiles:
  active: heroku
jackson:
  serialization:
    indent-output: true
datasource:
  type: com.zaxxer.hikari.HikariDataSource
  url: jdbc:postgresql://${HOST}/${DB_NAME}
  username: ${DB_USER}
  password: ${DB_PASSWORD}
jpa:
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  show-sql: false

mvc:
  pathmatch:
    matching-strategy: ant-path-matcher